import { createLog } from '../../logging';
import { addAgentMessage } from '../messages';
import { ASSISTANT_2_ID } from '../config';
import { QueryLogMessage } from './types';

export function createQueryBlockMessage({ query, ingredients, threadId }: QueryLogMessage): string {
  return `
╔════════════════════════════════════════════════════════════════════════════════
║ SQL QUERY GENERATED BY AGENT 2
║ Ingredients: ${ingredients}
║ Thread ID: ${threadId}
╠════════════════════════════════════════════════════════════════════════════════
║ ${query.split('\n').join('\n║ ')}
╚════════════════════════════════════════════════════════════════════════════════`;
}

export async function logSqlQuery(queryMessage: QueryLogMessage): Promise<void> {
  const blockMessage = createQueryBlockMessage(queryMessage);

  // Log to system logs
  await createLog('sql', ASSISTANT_2_ID, blockMessage, {
    thread_id: queryMessage.threadId,
    query: queryMessage.query,
    ingredients: queryMessage.ingredients,
    message_type: 'pre_execution'
  });

  // Add to agent messages for visibility
  addAgentMessage({
    id: Date.now().toString(),
    fromAgent: ASSISTANT_2_ID,
    toAgent: 'system',
    content: blockMessage,
    type: 'query',
    timestamp: Date.now(),
    threadId: queryMessage.threadId
  });
}